### ISSUE TITLE
how to set gcsbeat template?

### ISSUE THREAD

**Issue by hy2hh** [GoogleCloudPlatform/gcsbeat#9]
i got a message - "could not load template ..."  how to solve the problem? please example

**Comment by josephlewis42** [comment]
Would you explain a little more about what you mean by template? Are you looking for the search index patterns?

**Comment by hy2hh** [comment]
I checked the error message below.

`error instance/beat.go:674	exiting: error loading elasticsearch template: could not load template. elasticsearch returned: couldn't load template: clouldn't load json. error: 400 bad request ....`


I am testing the following example to store the stackdriver logs stored in elasticsearch.

```
Read Stackdriver logs from a bucket:

gcsbeat:
  bucket_id: my_log_bucket
  json_key_file: /path/to/key.json
  file_matches: "*.json"
  codec: "json-stream"
```

Is it a problem caused by the absence of index? How do I create the index? I'm asking because I don't know. I download and install binary files for use.

**Comment by josephlewis42** [comment]
It turns out the `fields.yml` file had an incorrect type in the index. You can change this near the bottom of the file (change 'int' to 'long' on line 192) or download the new release I just published. After that the index should be created correctly.

Let me know if that works, I'll mark this issue closed in a week if I don't hear anything and we can re-open if necessary.
